name: Languages Activity
on:
  # Schedule updates (At minute 0 past every 12th hour)
  schedule:
    - cron: "0 */12 * * *"
  # Lines below let you run workflow manually with each commit
  workflow_dispatch:
  push:
    branches:
      - master
      - main
      - metrics
jobs:
  # https://github.com/lowlighter/metrics/blob/master/source/plugins/languages/README.md
  language-activity-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Check runner compatibility
        run: |
          echo "Checking runner compatibility..."
          uname -a
      - name: Check out repository
        uses: actions/checkout@v2
      - uses: lowlighter/metrics@latest
        with:
          filename: assets/metrics.plugin.languages.activity.svg
          token: ${{ secrets.METRICS_TOKEN }} # Ensure this token has the necessary permissions
          base: ""
          plugin_languages: yes
          plugin_languages_ignored: >-
            tex, less, dockerfile, makefile, qmake, lex, cmake, shell,
            gnuplot
          plugin_languages_other: yes
          plugin_languages_sections: most-used
          plugin_languages_details: lines, percentage # Note that lines is only available when plugin_languages_indepth is enabled
          plugin_languages_limit: 8   # limit is 8
          plugin_languages_analysis_timeout: 15
